const categories = [
  {
    category: "Traditional Energy",
    firstData: "consumption",
    secondData: "location",
    endpoint: "traditionalHydro",
    optionSecond: [
      "USA",
      "Canada",
      "UK",
      "Europe",
      "Africa",
      "LatinAmerica",
      "MiddleEast",
      "OtherCountry",
    ],
    unitFirst: "KWH",
  },
  {
    category: "Public Transit",
    firstData: "distance",
    secondData: "type",
    endpoint: "publicTransit",
    optionSecond: [
      "Taxi",
      "ClassicBus",
      "EcoBus",
      "Coach",
      "NationalTrain",
      "LightRail",
      "Subway",
      "FerryOnFoot",
      "FerryInCar",
    ],
    unitFirst: "KM",
  },
  {
    category: "MotorBike",
    firstData: "distance",
    secondData: "type",
    endpoint: "motorBike",
    optionSecond: ["SmallMotorBike", "MediumMotorBike", "LargeMotorBike"],
    unitFirst: "KM",
  },
  {
    category: "Flight",
    firstData: "distance",
    secondData: "type",
    endpoint: "flight",
    optionSecond: [
      "DomesticFlight",
      "ShortEconomyClassFlight",
      "ShortBusinessClassFlight",
      "LongEconomyClassFlight",
      "LongPremiumClassFlight",
      "LongBusinessClassFlight",
      "LongFirstClassFlight",
    ],
    unitFirst: "KM",
  },
  {
    category: "Car Travel",
    firstData: "distance",
    secondData: "vehicle",
    endpoint: "carTravel",
    optionSecond: [
      "SmallDieselCar",
      "MediumDieselCar",
      "LargeDieselCar",
      "MediumHybridCar",
      "LargeHybridCar",
      "MediumLPGCar",
      "LargeLPGCar",
      "MediumCNGCar",
      "LargeCNGCar",
      "SmallPetrolVan",
      "LargePetrolVan",
      "SmallDielselVan",
      "MediumDielselVan",
      "LargeDielselVan",
      "LPGVan",
      "CNGVan",
      "SmallPetrolCar",
      "MediumPetrolCar",
      "LargePetrolCar",
    ],
    unitFirst: "KM",
  },
  {
    category: "Fuel To Carbon",
    firstData: "type",
    secondData: "litres",
    endpoint: "fuelToCO2e",
    optionFirst: ["Petrol", "Diesel", "LPG"],
    unitSecond: "l",
  },
  {
    category: "Clean Energy",
    firstData: "energy",
    secondData: "consumption",
    endpoint: "cleanHydro",
    optionFirst: [
      "Solar",
      "Wind",
      "HydroElectric",
      "Biomass",
      "Geothermal",
      "Tidal",
      "OtherCleanEnergy",
    ],
    unitSecond: "KWH",
  },
];

export default categories;
